AdminLTE.MVC/Controllers/EmployeeController.cs
using AdminLTE.Models;
using AdminLTE.Models.ViewModels;
using AdminLTE.MVC.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AdminLTE.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EmployeeController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Employee> employeeList = _db.Employees.Include(u => u.TerritorialCommunity);

            return View(employeeList);
        }

        public IActionResult Upsert(int? id)
        {
            EmployeeVM employeeVM = new EmployeeVM()
            {
                Employee = new Employee(),
                 TerritorialCommunitySelectList = _db.TerritorialCommunities.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };

            if (id == null)
            {
                return View(employeeVM);
            }
            else
            {
                employeeVM.Employee = _db.Employees.Find(id);
                if (employeeVM.Employee == null)
                {
                    return NotFound();
                }
                return View(employeeVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(EmployeeVM employeeVM)
        {

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;

                if (employeeVM.Employee.Id == 0)
                {
                    string upload = webRootPath + ENV.ImagePath;
                    string filename = Guid.NewGuid().ToString();
                    if (files.Count > 0)
                    {
                        string extentions = Path.GetExtension(files[0].FileName);

                        using (var fileStream = new FileStream(Path.Combine(upload, filename + extentions), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }

                        employeeVM.Employee.Photo = filename + extentions;
                    }
                    _db.Employees.Add(employeeVM.Employee);

                }
                else
                {
                    var formObject = _db.Employees.AsNoTracking().FirstOrDefault(u => u.Id == employeeVM.Employee.Id);
                    if (files.Count() > 0)
                    {
                        string upload = webRootPath + ENV.ImagePath;
                        string filename = Guid.NewGuid().ToString();


                        string extentions = Path.GetExtension(files[0].FileName);
                        if (formObject.Photo != null)
                        {
                            var oldFile = Path.Combine(upload, formObject.Photo);
                            if (System.IO.File.Exists(oldFile))
                            {
                                System.IO.File.Delete(oldFile);
                            }
                        }
                        using (var fileStream = new FileStream(Path.Combine(upload, filename + extentions), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        employeeVM.Employee.Photo = filename + extentions;

                    }
                    else
                    {
                        employeeVM.Employee.Photo = formObject.Photo;
                    }
                    _db.Employees.Update(employeeVM.Employee);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            employeeVM.TerritorialCommunitySelectList = _db.TerritorialCommunities.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });

            return View(employeeVM);
        }



        public IActionResult ConfirmDelete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Employee product = _db.Employees.Include(u => u.TerritorialCommunity).FirstOrDefault(u => u.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public IActionResult Delete()
        {
            IEnumerable<Employee> employeesList = _db.Employees.Include(u => u.TerritorialCommunity);

            return View(employeesList);
        }

        public IActionResult Edit()
        {
            IEnumerable<Employee> employeesList = _db.Employees.Include(u => u.TerritorialCommunity);

            return View(employeesList);
        }

        [HttpPost, ActionName("ConfirmDelete")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDeletePost(int? id)
        {
            var obj = _db.Employees.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            string upload = _webHostEnvironment.WebRootPath + ENV.ImagePath;
            if (!String.IsNullOrEmpty(obj.Photo))
            {
                var oldFile = Path.Combine(upload, obj.Photo);

                if (System.IO.File.Exists(oldFile))
                {
                    System.IO.File.Delete(oldFile);
                }
            }
            _db.Employees.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }


    }
}

AdminLTE.MVC/Controllers/TerritorialCommunityController.cs
using AdminLTE.MVC.Data;
using Microsoft.AspNetCore.Mvc;
using AdminLTE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminLTE.Controllers
{
    public class TerritorialCommunityController : Controller
    {
        private readonly ApplicationDbContext _db;
        public TerritorialCommunityController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<TerritorialCommunity> tcList = _db.TerritorialCommunities;
            return View(tcList);
        }
        public IActionResult Upsert(int? id)
        {
            TerritorialCommunity tc = new TerritorialCommunity();

            if (id == null)
            {
                return View(tc);
            }
            else
            {
                tc = _db.TerritorialCommunities.Find(id);
                if (tc == null)
                {
                    return NotFound();
                }
                return View(tc);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(TerritorialCommunity tc)
        {

            if (ModelState.IsValid)
            {
                if (tc.Id == 0)
                    _db.TerritorialCommunities.Add(tc);

                else
                    _db.TerritorialCommunities.Update(tc);


                _db.SaveChanges();
            
                return RedirectToAction("Index");
            }
            return View(tc);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            TerritorialCommunity tc = _db.TerritorialCommunities.FirstOrDefault(u => u.Id == id);
            if (tc == null)
            {
                return NotFound();
            }

            return View(tc);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var tc = _db.TerritorialCommunities.Find(id);
            if (tc == null)
            {
                return NotFound();
            }

            _db.TerritorialCommunities.Remove(tc);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }

    }
}

AdminLTE.MVC/Views/Shared/AdminLTE/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

AdminLTE.MVC/Views/Shared/AdminLTE/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title> @ViewData["Title"] </title>
 
    <partial name="AdminLTE/_Styles" />
</head>
<body class="hold-transition  sidebar-collapse">
    <div class="wrapper">
        <partial name="AdminLTE/_TopNavigation" />
        <partial name="AdminLTE/_MainNavigation" />
        <div class="content-wrapper">
    
            <div class="content">
                <div class="container-fluid py-3">
                    @RenderBody()
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <partial name="AdminLTE/_Footer" />
    </div>
    <partial name="AdminLTE/_Scripts" />
</body>
</html>

AdminLTE.MVC/Views/Shared/AdminLTE/_MainNavigation.cshtml
@using static AdminLTE.MVC.Helpers.NavigationIndicatorHelper;
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="~/Home" class="brand-link">
        <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
    <div class="sidebar">
    
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item ">
                    <a asp-controller="Home" asp-action="Index" class="nav-link @Url.MakeActiveClass("home","index")">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Home
                        </p>
                    </a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                         <li class="nav-item">
                             <a  class="nav-link">
                                 <i class="nav-icon fas fa-users"></i>
                                 <p>
                                     Emoloyees
                                     <i class="right fas fa-angle-left"></i>
                                 </p>
                             </a>
                             <ul class="nav nav-treeview" style="display: none;">
                                 <li class="nav-item">
                                     <a asp-area="" asp-controller="Employee" asp-action="Index" class="nav-link">
                                         <i class="far fa-circle nav-icon"></i>
                                         <p>All</p>
                                     </a>
                                 </li>
                                 <li class="nav-item">
                                     <a asp-area="" asp-controller="Employee" asp-action="Upsert" class="nav-link">
                                         <i class="far fa-circle nav-icon"></i>
                                         <p>Add</p>
                                     </a>
                                 </li>
                                 <li class="nav-item">
                                     <a asp-area="" asp-controller="Employee" asp-action="Edit" class="nav-link">
                                         <i class="far fa-circle nav-icon"></i>
                                         <p>Edit</p>
                                     </a>
                                 </li>
                                 <li class="nav-item">
                                     <a asp-area="" asp-controller="Employee" asp-action="Delete" class="nav-link">
                                         <i class="far fa-circle nav-icon"></i>
                                         <p>Remove</p>
                                     </a>
                                 </li>

                             </ul>
                         </li>
                         <li class="nav-item">
                             <a asp-area="" asp-controller="TerritorialCommunity" asp-action="Index" class="nav-link">
                                 <i class="nav-icon fas fa-place-of-worship"></i>
                                 <p>
                                     Territorial Comunities                        
                                 </p>
                             </a>                
                         </li>
                        
                        
                         <li class="nav-item ">
                             <a asp-controller="Home" asp-action="Privacy" class="nav-link @Url.MakeActiveClass("home","privacy")">
                                 <i class="nav-icon fas fa-lock"></i>
                                 <p>
                                     Privacy
                                 </p>
                             </a>
                         </li>
                         }
                                 </ul>
                             </nav>
    </div>
</aside>

AdminLTE.MVC/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/adminlte.min.js"></script>

AdminLTE.MVC/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

AdminLTE.MVC/Views/Shared/AdminLTE/_TopNavigation.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item ml-0 ml-sm-auto">
        <a asp-area="Identity" asp-page="/Account/Register" class="nav-link">Register</a>
    </li>
    <li class="nav-item ">
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item ml-0 ml-sm-auto">
        <a asp-area="Identity" asp-page="/Account/Login" class="nav-link">Login</a>
    </li>
}

    </ul>

    <!-- Right navbar links -->
    <!--<ul class="navbar-nav ml-auto">-->
        <!-- Messages Dropdown Menu -->
        <!--<li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">-->
                    <!-- Message Start -->
                    <!--<div class="media">
                        <img src="/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>-->
                    <!-- Message End -->
                <!--</a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">-->
                    <!-- Message Start -->
                    <!--<div class="media">
                        <img src="img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>-->
                    <!-- Message End -->
                <!--</a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">-->
                    <!-- Message Start -->
                    <!--<div class="media">
                        <img src="img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>-->
                    <!-- Message End -->
                <!--</a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>-->
        <!-- Notifications Dropdown Menu -->
        <!--<li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>-->
</nav>
<!-- /.navbar -->